# Generated by Django 5.1.1 on 2024-09-13 06:50

import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField()),
            ],
            options={
                'db_table': 't_user',
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('User'), models.Model),
        )
    ]
